manifests/init.pp

rather than hard coded to 7.  This makes this compatible with older
versions of RHEL

Changed the addition repos to be based on ${::operatingsystemmajrelease}

---

manifests/repo.pp

Puppet has a built-in resource type to manage YUM repository. The subscription-manager generates all the Red Hat repo configuration in a single file. Using the Puppet resource type 'target' parameter allows to manage this generated list with the resource type.

Use built-in Yumrepo resource type instead of Exec

---

metadata.json

In response to #16 
Would be nice if Puppet allowed us to set lower/upper version boundaries in supported OS.
I added RHEL 5.7 (not listing all the way to 5.11) to flag the module for any user who might still run RHEL 5 and looks for help managing RHSM. But in reality subscription-manager is available in RHEL 5.7 and above, RHEL 6 got it in 6.1.
https://access.redhat.com/solutions/253273

Remove CentOS from target OS list and added RHEL 5.7

---

manifests/init.pp

To be able to change an expired subscription (for example) on an already registered system, the two tasks needed to be separated.
While at it, '/usr/sbin' was added to the path to shorten the command executed and onlyif conditions in the Exec resources.
There might be an edge case where a registered system with an active subscription gets a new poolid value assigned by Puppet but that won't be updated on the node. That was already a problem the module couldn't handle before and should probably the next step now that subscription is separated from registration.

Separated Registration and Subscription tasks

---

metadata.json

We currently only run automated tests against Puppet 3 latest and
therefore cannot guarantee that this module works as is expected with
earlier Puppet versions
Bump stdlib to the minimum version that should work under Puppet 4,
based on the metadata

Set min version_requirement for Puppet + bump dep

---

manifests/init.pp
spec/classes/init_spec.rb

Add org and activationkey paramters, do not require rh_user and rh_password if org and activationkey are provided.
I also modified way commands are built so that unit tests don't have to be padded with empty spaces.

Add org and activationkey paramters

---

manifests/init.pp

Added 'Expired' to cover cases where a valid subscription expired and the module should trigger a new subscription on nodes not meant to use auto-attach.

Add 'Expired' in grep to trigger subscription

---

lib/facter/rhsm_repos.rb

Without this, any other node than Red Hat (could be Windows) with this module in its node classification would have the Puppet Ruby runtime attempting to execute this Fact.

Added confine rule on Fact

---

manifests/init.pp
spec/classes/init_spec.rb

Change servername to subscription.rhsm.redhat.com and rename RHNSM to RHSM

Change servername to subscription.rhsm.redhat.com

---

README.md
manifests/init.pp
manifests/repo.pp

Change documentation syntax to YARD/Puppet Strings and update rhsm template
Optimize README for puppet strings
Red Hat disabled the old Red Hat Network (RHN), so servername is changed from subscription.rhn.redhat.com to subscription.rhsm.redhat.com

Change documentation syntax to YARD/Puppet Strings and update template

---

manifests/init.pp
templates/rhsm.conf.erb

Configurable parameters are needed when using Red Hat Satellite 6 or SAM
This addresses issue #11

Update rhsm.conf template (5.15.1) and add configurable params

---

manifests/init.pp

manage_repos is already used in the template `rhsm.conf.erb` but not specified.

Add missing parameter manage_repos

---

README.md
manifests/init.pp
templates/rhsm.conf.erb

When using Red Hat Satellite 6 one needs to change the rhsm certificates.
`README.md` has an example usage with Red Hat Satellite 6.
Closes #11 and #6

Add params for adding custom certificates

---

manifests/init.pp
manifests/repo.pp
spec/classes/init_spec.rb
spec/defines/repo_spec.rb

When using the rhsm::repo type outside of this module,
one does not have to worry about requiring `Exec['RHSM-subscribe']`.
n/a

Move RHSM-subscribe dependency inside repo type

---

README.md
lib/puppet/provider/rh_repo/redhat.rb
lib/puppet/provider/rh_subscription/redhat.rb
lib/puppet/type/rh_repo.rb
lib/puppet/type/rh_subscription.rb

This PR introduces types and providers used in @crayfishx 's puppet-rhsm.
This is useful if you need to enable additional subscriptions (products on Satellite 6) through Puppet (not only by the use of an activation key or multiple activation keys).
Fixes #87

Add types and providers from crayfishx/puppet-rhsm

---

manifests/init.pp
templates/rhsm.conf.erb

Add defaults from subscription-manager 1.21.10
Make two of them configurable:
* inotify
* server_timeout
server_timeout is measured per http call, not the overall time of a subscription-manager run. The default of 180s might lead to puppet run issues (`subscription-manager repos --list-enabled` is used in the rhsm fact, this command triggers 7+ http connections).
Fixes #85

Add defaults and make server_timeout and inotify configurable

---

manifests/init.pp
metadata.json

Add Sensitive to RHSM exec and update metadata

---

spec/classes/init_spec.rb

This fixes unit tests for rspec-puppet 2.8.

fix: use sensitive() for rspec-puppet 2.8

---

README.md
REFERENCE.md
manifests/init.pp
spec/classes/init_spec.rb
templates/rhsm.conf.erb

add no_proxy to rhsm.conf, defaults to undef

---

manifests/init.pp
spec/classes/init_spec.rb

This is mostly a sanity check, but, if you've set `file` to have
a default `mode` without world read, you'll get an error from
yum/dnf about this.

Ensure dnf/yum plugin config has read.

---

manifests/init.pp
spec/classes/init_spec.rb

If you set /etc/yum.repos.d/ to `purge => true` it is helpful if puppet knows to leave redhat.repo alone.
N/A

When purging unmanaged repos, this file needs to be known to puppet.

---

manifests/init.pp
spec/classes/init_spec.rb

In part this was added as a way to mirror the behavior added to the yum module.  Folks who don't want to track yum repos in this manner can avoid the resource declaration.

Add a switch to prevent caring about redhat.repo if needed

---

lib/facter/rhsm.rb

This PR adds support to provide the rhsm.available_repo_ids fact, containing all available repository ids.
Fixes #132

add fact for rhsm.available_repo_ids

---

REFERENCE.md
manifests/init.pp
spec/classes/init_spec.rb

This PR adds a parameter to the `rhsm` class to define subscription IDs via hiera. This fixes an observed issue in our environment where some repositories require subscriptions which were not attached at registration time. This allows adding them programmatically via hiera, same as is currently possible for repositories.
I added test cases for the new parameter, and added the parameter to the reference documentation as well. Let me know if anything more is needed.
N/A

Allow subscriptions to be attached via hiera

---

manifests/init.pp

This introduces conditional logic to detect if sensitive/secret values may be passed in as Deferred type, and if so to process them entirely through a chain of Deferred arguments, to address issues with interpolating Deferred into strings on the compiler.
Unfortunately, there is no way at the moment to pass a parameter of type Deferred into puppet-rspec, so while this has been tested and verified locally, there is not currently a unit test for this new functionality.
n/a

Allow the user/pw or org/key to be Deferred.
