lib/rhsm_repos.rb, manifests/init.pp, manifests/repo.pp
* improved checks for registration and enabled repository
* created fact for enabled rhsm repos
* wider testing
=> General Improvements-revised

CHANGELOG.md, metadata.json
=> release 0.3.0

.msync.yml, Gemfile, Rakefile, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 0.11.0

README.md
Added proxy related examples and removed old table of content which wasn't very useful and listed non existing elements. As requested in #12
=> Added documentation for HTTP proxy settings

manifests/init.pp
Added '/usr/bin' to path for Exec as it might be needed by some RHEL version depending on where grep is installed.
=> Added '/usr/bin' to path for Exec

CHANGELOG.md, README.md, metadata.json
=> release 1.0.0

.msync.yml, .pmtignore, .travis.yml, .yardopts, Gemfile, Rakefile, metadata.json, spec/acceptance/nodesets/centos-6-x64.yml, spec/acceptance/nodesets/centos-7-x64.yml, spec/acceptance/nodesets/docker/centos-7.yml, spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml, spec/acceptance/nodesets/ec2/image_templates.yaml, spec/acceptance/nodesets/ec2/rhel-73-x64.yml, spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml, spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml, spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml, spec/spec_helper.rb
=> Modulesync 0.20.0

manifests/init.pp
Based on issue reported and with suggested fix from #38
=> Read from both stdout and stderr for Exec onlyif

.github/CONTRIBUTING.md, .msync.yml, .overcommit.yml, .rubocop.yml, .travis.yml, Gemfile, spec/classes/init_spec.rb
=> modulesync 0.21.0

manifests/repo.pp
See https://docs.puppet.com/puppet/latest/type.html#yumrepo-attribute-enabled
=> The yumrepo parameter `enabled` had a typo.

.travis.yml, CHANGELOG.md, metadata.json
=> Release 2.0.0

lib/facter/rhsm_repos.rb
=> Use subscription-manager instead of yum for listing enabled repos

manifests/repo.pp
Changed enabled => true to enabled => '1'
=> Update repo.pp (#58)

lib/facter/rhsm_subscription_type.rb
=> Add rhsm_subscription_type fact

.msync.yml, Dockerfile, Gemfile, Rakefile, examples/init.pp, spec/spec_helper.rb
=> modulesync 2.7.0

.travis.yml
=> travis: dont upgrade bundler

lib/facter/rhsm.rb
Some organizations may have more than one Satellite server and it would be useful to have a fact with that information.
=> Add server info to facts

manifests/init.pp, templates/rhsm.conf.erb
Add `processTimeout` to `rhsm.conf`. This value is primarily used on RHEL 7.8 systems.
=> Add process_timeout parameter

.fixtures.yml, .github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, .puppet-lint.rc, Dockerfile, Gemfile, Rakefile, lib/facter/rhsm.rb, lib/puppet/provider/rh_repo/redhat.rb, lib/puppet/provider/rh_subscription/redhat.rb, lib/puppet/type/rh_repo.rb, lib/puppet/type/rh_subscription.rb, metadata.json, spec/classes/init_spec.rb, spec/spec_helper.rb
=> modulesync 5.2.0 / Drop EoL Puppet 5 support

README.md, REFERENCE.md, manifests/init.pp, spec/classes/init_spec.rb, templates/ini.conf.epp
With EL8+ the `dnf` plugin has gained a few features that are nice to set.  This adds a parameter to allow folks to configure those settings easily.
I'll confess I don't like the name I ended up with very much...
=> Add way to configure the dnf/yum plugin

CHANGELOG.md, metadata.json
=> Release 5.2.0

CHANGELOG.md, metadata.json
=> Release 5.3.0

lib/facter/rhsm.rb
This should parse out the `syspurpose.json` if defined and add those entries to the facts reported.
Fixes: #120
=> Add syspurpose entries to facts

.github/CONTRIBUTING.md, .github/labeler.yml, .github/release.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, .github/workflows/prepare_release.yml, .github/workflows/release.yml, .msync.yml, .pmtignore, .puppet-lint.rc, Gemfile, spec/classes/init_spec.rb, spec/spec_helper.rb
=> modulesync 10.0.0
